### ISSUE TITLE
When using this plugin ctags spawned processes are taking over 100% cpu

### ISSUE THREAD

**Issue by ZzAntares** [shawncplus/phpcomplete.vim#77] opened 2015-10-08 22:06 UTC
Whenever I use this plugin, and I'm working with vim, some ctags processes are spawned  (like 5 ctags processes) and every one of them are taking up to 80%-100% of CPU usage.

At first I thought it was the [patched fork](https://github.com/b4n/ctags/tree/better-php-parser) of ctags, so I uninstalled it, and keep exhuberant ctags, but the behaviour is the same.

I'm using Mac OSX 10.10.5 and Vim 7.4. What can I do?

**Comment by complex857** [comment] 2015-10-09 05:50
Is this happening with every code base or only on some specific ones?
I've experienced something like this (never ending ctags indexing) but only with my ctags patches on the [mkusher/padawan.php](https://github.com/mkusher/padawan.php) project.

If you can pinpoint it to a file or project, can you send me the code in question?

**Comment by ZzAntares** [comment] 2015-10-12 22:03
Sorry but seems the problem was not with this plugin, I'm suspecting the problem comes from vim itself, may be the bundled phpcomplete.

**Comment by complex857** [comment] 2015-10-13 06:46
I'm still pretty much interested in reproducing this, since I'm the maintainer of the bundled version too, if it's buggy i want to know about it pretty much (-:

**Comment by ZzAntares** [comment] 2015-10-13 22:18
Ok, what we can do to see where is the problem because I don't know where the problem is, as soon as I install ctags and use vim, some minutes latter the CPU process are over 80%-100%.

**Comment by complex857** [comment] 2015-10-14 07:19
I understand. The plugin itself never calls ctags directly, so I'm not sure what to make of this yet. 

Do you have vim-tagbar or some other plugin that would call ctags to regenerate tags when saving files, or generate tags when you are opening one? I would try to disable them (one-by-one) and see if the problem goes away so you can pinpoint it to one of them.

If that isn't it, do this happens even if you don't trigger completion? By default this plugin doesn't do anything until it's called by either with <kbd>ctrl</kbd>+<kbd>x</kbd>,<kbd>ctrl</kbd>+<kbd>o</kbd> or by some other plugin like YouCompleteMe, supertab, neocomplete.

You can try to check `top` or something like that to see if it's the vim process or a ctags process that uses the cpu when it happens too.

**Comment by ZzAntares** [comment] 2015-10-22 04:17
I have been working without issues now, I updated to Mac OS X 10.11, I'm pretty sure phpcomplete is not the problem as I was thinking, very well could be "szw/vim-tags" is my principal suspect.

**Comment by complex857** [comment] 2015-10-22 07:15
I see, thank you for the followup. I'm gonna close this then.

**Closed by complex857** 2015-10-22 07:15 UTC
